version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
      #nginx配置默认安装到/etc/nginx/conf，静态页面默认到/usr/share/nginx/html
    - ./nginx/conf:/etc/nginx/conf
    - ./nginx/nginx.html:/usr/share/nginx/html/index.html

  mysql:
    container_name: v-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  #app:
    #restart: always
    #build: ./app
    #working_dir: /app
    #volumes:
    #- ./app:/app
    #- ~/.m2:/root/.m2
    #- "8080"
    #depends_on:
    #- nginx
    #- mysql
    #command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker

    #常用命令：
    #1.   docker exec -it v-mysql /bin/bash  ：宿主机与容器交互
    #2.   其中proxy_pass http://app:8080这块的配置信息需要解释一下，这里使用是app而不是localhost，是因为他们没有在一个容器中，在一组 compose 的服务通讯需要使用 services 的名称进行访问。
    #3.   将数据库的连接信息由jdbc:mysql://localhost:3306/test改为jdbc:mysql://mysql:3306/test 。
    #4.    查看端口：lsof -i:8082，查看进程：ps -ef | grep jaav